apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-lab-static
  labels:
    lab: storage-homelab
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/k8s-lab/storage/static
    type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-lab-static-2
#   labels:
#     lab: storage-homelab
#     tier: secondary
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   hostPath:
#     path: /var/lib/k8s-lab/storage/static-2
#     type: DirectoryOrCreate
