apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: storage-lab
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: 10Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pvc-limits
  namespace: storage-lab
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 5Gi
      min:
        storage: 100Mi
